export const endpoints = {
  login: "sessions",
  adminSignUp: "admin",
  createMember: "members",
  getSessions: "sessions",
  verifySession: "sessions",
  getProjects: "projects",
  createProject: "projects",
  getTopFourProjectsWithMostMembers: "projects-overview",
  getProjectById: "projects",
  updateProjectById: "projects",
  accountStats: "stats",
  getUserTickets: "user/tickets",
  getMembers: "members",
  getAllMembers: "allmembers",
  createTicket: "tickets",
  getProjectTickets: "project/tickets",
  getTicketById: "tickets",
  updateTicketById: "tickets",
  deleteProjectById: "projects",
  deleteTicketById: "tickets",
};
