version: "3.7"
services:
  bug-tracker-api:
    container_name: bug-tracker-api
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    build:
      context: ./
    ports:
      - "4000:4000"
